language: node_js

node_js:
  - "8.9.4"

install:
  - npm -g install yarn
  - yarn
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - yarn run test
  
 after_script:
  - ./cc-test-reporter format-coverage --input-type lcov --output coverage/codeclimate.js.json coverage/karma/lcov.info
  - ./cc-test-reporter upload-coverage --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - ~/.yarn
    - ~/.nvm
